### PR TITLE
feat: :sparkles: Added multiple materials from both camps and changed…

### PR DESCRIPTION
**Pull request by hhzzff**
… ship textures.

  

- [x] 您的代码是否能够编译通过？
- [x] 您是否检查了目前在 [pull requests](https://github.com/eesast/THUAI7/pulls) 中是否有与你的贡献功能相同的更改？
- [x] 您的贡献是否符合[贡献者代码协议](https://github.com/eesast/THUAI7/blob/dev/CODE_OF_CONDUCT.md)？
- [x] 您的贡献是否符合[开发规则](https://github.com/eesast/THUAI7#%E5%BC%80%E5%8F%91%E8%A7%84%E5%88%99)？  

Descriptions of this pull request:

No additional description.

### CODE REVIEW

**Review by Panxuc — APPROVED** [review]

**Comment by Panxuc** [comment]
Can the color part of the texture be separated in order to produce more color varients?

**Comment by asdawej** [comment]
> Can the color part of the texture be separated in order to produce more color varients?

The color part of the textures may be too complex to be seperated. It should get the balance between the texture seperation along with more complex system and the drawing work.

**Comment by Panxuc** [comment]
> > Can the color part of the texture be separated in order to produce more color varients?
> 
> The color part of the textures may be too complex to be seperated. It should get the balance between the texture seperation along with more complex system and the drawing work.

Simply adding a mask will work, I suppose. It is not that complex.

**Comment by asdawej** [comment]
> > > Can the color part of the texture be separated in order to produce more color varients?
> > 
> > 
> > The color part of the textures may be too complex to be seperated. It should get the balance between the texture seperation along with more complex system and the drawing work.
> 
> Simply adding a mask will work, I suppose. It is not that complex.

I'll make it an issue.

**Pull request merged**
